# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.15.8
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run tests
          command: |
            mkdir -p /tmp/test-reports
            gotestsum --junitfile /tmp/test-reports/unit-tests.xml
      - store_test_results:
          path: /tmp/test-reports
      - run:
          name: Make
          command: make build
      - store_artifacts:
          path: "./bootstrap"
          destination: bootstrap.zip
      - persist_to_workspace:
          root: "./"
          paths:
            - bootstrap.zip

  deploy:
    docker:
      - image: cimg/node:16.10.0
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/build

      - run:
          name: Move code from attached workspace
          command: |
            mv /tmp/build/* ./

      - run: ls

      - restore_cache:
          keys:
            - serverless-dependency

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: serverless-dependency

      - run:
          name: Deploy API to AWS
          command: |
            ./node_modules/.bin/sls deploy

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main